# Generated by Django 3.2.5 on 2021-07-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='expense_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
