# Generated by Django 3.1.6 on 2021-07-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210720_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01'),
            preserve_default=False,
        ),
    ]
