# Generated by Django 3.2.5 on 2021-07-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_month_expense_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='description',
        ),
    ]
