# Generated by Django 3.1.6 on 2021-07-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210720_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='total_saved',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=20),
            preserve_default=False,
        ),
    ]
