# Generated by Django 3.2.5 on 2021-07-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210720_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_saved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
