# Generated by Django 3.2.5 on 2021-07-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210720_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
